name: Rubocop linting

on: pull_request

jobs:
  lint:
    name: rubocop
    runs-on: ubuntu-20.04
    container:
      image: ruby:3.0.0
    steps:
      - uses: actions/checkout@v3
      - name: rubocop
        run: bundle exec rubocop --parallel